### ISSUE TITLE
Wandi/EasyAdminPlusBundle fork

### ISSUE THREAD

**Issue by jacquesndl** [2lenet/EasyAdminPlusBundle#12]
Hello 2lenet, 
I'm very surprised. Why did you create a side project based on a fork instead of implementing (or improving) features on the main project (even more without mention)? This is not really the spirit of an open source project.

**Comment by sebheitzmann** [comment]
Hi, I have done some pull request in the project start. You're still mentionned on the author list.

I'm sorry if you feel that i don't respect your work. It's not the case.

But we added a lot of new fonctionnality. Maybe we could colaborate on the evolution.

**Comment by jacquesndl** [comment]
Thanks to 2lnet for your beautiful contributions to the open source world.
