### ISSUE TITLE
Error with create link on list page

### ISSUE THREAD

**Issue by moux2003** [2lenet/EasyAdminPlusBundle#13]
I'm getting an error wjen using your bundle with the link of the create action on list page.
I don't know if I missed some configuration but the issue is on this line:
https://github.com/2lenet/EasyAdminPlusBundle/blob/700af61b5a5770115de42cc7176daf6367e3174a/src/Resources/views/default/list.html.twig#L62

should be `merge({ action: _action.name }))`

**Comment by sebheitzmann** [comment]
I don't have this error. I will see if i can reproduce this.

**Comment by sebheitzmann** [comment]
can you provide me your entity config ?

**Comment by moux2003** [comment]
No issues anymore thanks to commit 619382efd08a83919e96c7a776247c0697587e63
