### ISSUE TITLE
Compatibility with EasyAdmin 2 ?

### ISSUE THREAD

**Issue by mthiebaut** [2lenet/EasyAdminPlusBundle#24]
Hello,

Do you think to create a new version to make this bundle compatible with EasyAdmin 2 ?

Thank you

**Comment by christopher87** [comment]
Hi,

Any answer to that question please ?
I'm interested.

Thanks in advance.

**Comment by mthiebaut** [comment]
Hello @christopher87 ,

Finally I did'nt use this bundle =)

**Comment by jorissae** [comment]
Hello 

This is a problem that we currently study, maybe we make it compatible with EasyAdmin 3 directly.

Of course, we accept some help :-)

@mthiebaut  why did you stop using EasyAdminPlus ?
