### ISSUE TITLE
Easy Admin 3 Compatibilit

### ISSUE THREAD

**Issue by janthomas89** [2lenet/EasyAdminPlusBundle#47]
Thank you for this great Bunde. Especially the tree component is very valuable for our admin dashboards. As Easy Admin 3 was releasesd in June 2020, I am curious if there are any plans regarding Easy Admin 3 compatibility?

Thank you!

**Comment by jorissae** [comment]
I'm sorry but we didn't plan for easyadmin 3 but we are thinking about it.
